### ISSUE TITLE
Data Access

### ISSUE THREAD

**Issue by mfansler** [hirosome/2023-trap-upr#1]
Searching DDBJ for `DRA015587` yields no result. Is the data currently embargoed? If so, is there a timeline for releasing?

Thank you for the very interesting work!

**Comment by hirosome** [comment]
Sorry for the inconvenience. `DRA015587` has been made public. Data can be accessed via DDBJ Search.

**Comment by mfansler** [comment]
Thank you for making this available! I confirm the data is now accessible.
